// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnxhyEBcWU_0Yu8jvDdXT7ZW6AbuHRks',
    appId: '1:549009234368:android:d83906586b6f22ab725025',
    messagingSenderId: '549009234368',
    projectId: 'e-commerce-app-9fdfa',
    storageBucket: 'e-commerce-app-9fdfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Cl_PKlLHqBispSWq-MhTMapyO_hIpeo',
    appId: '1:549009234368:ios:38437e6fc77ae579725025',
    messagingSenderId: '549009234368',
    projectId: 'e-commerce-app-9fdfa',
    storageBucket: 'e-commerce-app-9fdfa.firebasestorage.app',
    androidClientId: '549009234368-ub370i76qq3nbi6jd1luhg13sve6mbef.apps.googleusercontent.com',
    iosClientId: '549009234368-iuqbrsuo9vmhki0rnudngva6lvnomugh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}